name = "portfolio"
type = "webpack"
route = ''
account_id = "1bda26fe457ea7a9dcd193e268e07770"
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "dist",entry-point = "workers-site"}
compatibility_date = "2022-01-07"
