// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Contact: typeof import('./components/Sections/Contact.vue')['default']
    Container: typeof import('./components/layout/Container.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    GithubProjects: typeof import('./components/GithubProjects.vue')['default']
    Navbar: typeof import('./components/layout/Navbar.vue')['default']
    PortfolioCard: typeof import('./components/PortfolioCard.vue')['default']
    SectionHeader: typeof import('./components/SectionHeader.vue')['default']
    Toast: typeof import('./components/layout/Toast.vue')['default']
  }
}

export { }
