// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./components/layout/Container.vue')['default']
    Navbar: typeof import('./components/layout/Navbar.vue')['default']
    Toast: typeof import('./components/layout/Toast.vue')['default']
  }
}

export { }
