name: Build project

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - adonis
    paths:
      - 'client/**'

jobs:
  run:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Move to working dir
        run: cd client
        
      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Demian
          author_email: devaccdemiann@gmail.com
          message: 'Rebuild Client'
          add: 'build'
